### ISSUE TITLE
Warning [2] Undefined array key "before" - Line: 905 - File: inc/plugins/pluginlibrary.php PHP 8.1.29 (Linux)

### ISSUE THREAD

**Issue by huckleberrypie** [mybbgroup/MyBB-Google-SEO#12]
Title should say all. I am getting the following error upon updating my PHP version to PHP8. I already updated the plugin to account for that version but this one's still showing up.
![Screenshot 2024-07-18 at 11-21-08 Plugins](https://github.com/user-attachments/assets/7a293b78-3c9c-4d06-80b0-77dfa3c9a9e9)

**Comment by lairdshaw** [comment]
That's a problem with PluginLibrary, not Google SEO, and, yes, we've got an updated version of that for you too:

https://github.com/mybbgroup/MyBB-PluginLibrary

**Comment by huckleberrypie** [comment]
> That's a problem with PluginLibrary, not Google SEO, and, yes, we've got an updated version of that for you too:
> 
> https://github.com/mybbgroup/MyBB-PluginLibrary

Thanks for the tip, but now I am getting this one:
![Screenshot 2024-07-18 at 13-47-31 Strawberryland Forum - Members Lounge](https://github.com/user-attachments/assets/a1b16403-7a9c-41f4-b9bc-164090527196)

**Comment by lairdshaw** [comment]
That's unrelated to either plugin. It could be a theme problem. Which theme are you using?

**Comment by huckleberrypie** [comment]
Hmm, I'm just using the default theme for now.

**Comment by lairdshaw** [comment]
Got any plugins that might have inserted the `$inline_edit_js` variable into `forumdisplay_threadlist` template?

And is this a new install or have you upgraded? If you've upgraded, have you run Find Updated Templates?

**Comment by huckleberrypie** [comment]
These are all the plugins I have at the moment. I am not sure if they poke into the variables you speak of.

![Screenshot 2024-07-18 at 16-00-52 Plugins](https://github.com/user-attachments/assets/0adc8573-c9ac-4d3e-85b9-a909d186f716)
![Screenshot 2024-07-18 at 16-01-12 Themes](https://github.com/user-attachments/assets/2afd9094-88b5-4d00-a3b6-09d15e6e1c83)

**Comment by lairdshaw** [comment]
I did some digging and discovered that the `$inline_edit_js` variable was removed from the `forumdisplay_threadlist` template in the upgrade to MyBB 1.8.38. You should simply remove it from that template. Running Find Updated Templates after each upgrade shows you changes like this that need to be made.

**Comment by huckleberrypie** [comment]
> I did some digging and discovered that the `$inline_edit_js` variable was removed from the `forumdisplay_threadlist` template in the upgrade to MyBB 1.8.38. You should simply remove it from that template. Running Find Updated Templates after each upgrade shows you changes like this that need to be made.

I see, thanks for the heads up.

**Comment by lairdshaw** [comment]
No worries. I'm now closing this issue.
